name: Master/Stable

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
    - '*.md'
    - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upgrade Chrome browser
      run: |
        sudo apt-get update
        sudo apt-get --only-upgrade install google-chrome-stable

        google-chrome --version
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.16.1'
    - name: Install dependencies
      run: npm install
    - name: Build package
      run: npm build
    - name: Run tests
      run: npm run test-with-coverage
